// app/page.tsx
import { LandingAuth } from "@/components/auth/LandingAuth";
import Link from "next/link";
import { dm_serif, dm_sans } from "@/lib/fonts/fonts";
import PlaybackDemo from "@/components/landing/demo/PlaybackDemo";
import { demoRecordingData } from "@/components/landing/demo/demo-recording";
import { Button } from "@/components/ui/button";

export default function Home() {
	return (
		<div className="bg-black">
			<main>
				{/* Hero Section */}
				<section className="flex flex-col items-center justify-center text-center h-screen">
					<h1
						className={`${dm_serif.className} text-4xl sm:text-4xl md:text-5xl lg:text-7xl text-vivid tracking-normal mb-10`}
					>
						Addie
					</h1>
					<p
						className={`${dm_sans.className} max-w-[1000px] text-3xl sm:text-3xl md:text-5xl lg:text-7xl text-sec/50 mb-16`}
					>
						Create{" "}
						<span className="text-sec">beautiful voice ads</span>{" "}
						for podcasts and radio{" "}
						<span className="text-sec">in minutes</span>
					</p>
					<Button
						asChild
						size="lg"
						className="mb-16 px-12 text-2xl h-14 rounded-full bg-vivid hover:bg-vivid hover:scale-105 transition-all text-black"
					>
						<Link href="/auth">Get Started</Link>
					</Button>
				</section>

				{/* How it works heading */}
				<h2
					className={`${dm_sans.className} text-4xl md:text-5xl text-vivid text-center mb-12 mt-20`}
				>
					How it works
				</h2>

				{/* Step 1: Choose ad duration and speakers */}
				<section className="min-h-screen flex flex-col items-center justify-center px-4 py-20">
					<div className="max-w-3xl text-center">
						<h3
							className={`${dm_sans.className} text-2xl text-vivid mb-4`}
						>
							Step 1: Choose ad duration and speakers
						</h3>
						<p className={`${dm_sans.className} text-lg text-sec`}>
							Select the ad length and pick the voices that best
							suit your brand.
						</p>
					</div>
				</section>

				{/* Step 2: Describe your ad */}
				<section className="min-h-screen flex flex-col items-center justify-center px-4 py-20">
					<div className="max-w-3xl text-center">
						<h3
							className={`${dm_sans.className} text-2xl text-vivid mb-4`}
						>
							Step 2: Describe your ad
						</h3>
						<div className="bg-gray-900/50 border border-gray-800 p-8 rounded-2xl h-[200px] flex items-center justify-center backdrop-blur-sm transition-all hover:border-vivid/30 hover:bg-gray-900/70 w-full mt-6">
							<p
								className={`${dm_sans.className} text-3xl text-sec`}
							>
								"Create an ad for the new IKEA kids furniture
								collection"
							</p>
						</div>
					</div>
				</section>

				{/* Step 3: Ad generated by AI */}
				<section className="min-h-screen flex flex-col items-center justify-center px-4 py-20">
					<div className="max-w-3xl text-center">
						<h3
							className={`${dm_sans.className} text-2xl text-vivid mb-4`}
						>
							Step 3: Ad generated by AI
						</h3>
						<div className="border border-gray-800 rounded-2xl overflow-hidden transition-all hover:border-vivid/30 w-full mt-6">
							<PlaybackDemo
								jsonPath="/example_recordings/recording-UCdMzmUVLdWwD6yEzstsZVrHeZo2-o9pp4Nv4RF7LZIRXZrq2.json"
								description=""
							/>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
