// app/page.tsx
import { LandingAuth } from "@/components/auth/LandingAuth";
import Link from "next/link";
import { dm_serif, dm_sans } from "@/lib/fonts/fonts";
import PlaybackDemo from "@/components/landing/demo/PlaybackDemo";
import { demoRecordingData } from "@/components/landing/demo/demo-recording";
import { Button } from "@/components/ui/button";

export default function Home() {
	return (
		<div className="bg-black">
			<main>
				{/* Hero Section */}
				<section className="flex flex-col items-center justify-center text-center h-screen">
					<h1
						className={`${dm_serif.className} text-4xl sm:text-4xl md:text-5xl lg:text-7xl text-vivid tracking-normal mb-10`}
					>
						Addie
					</h1>
					<p
						className={`${dm_sans.className} max-w-[1000px] text-3xl sm:text-3xl md:text-5xl lg:text-7xl text-sec/50 mb-16`}
					>
						Create{" "}
						<span className="text-sec">beautiful voice ads</span>{" "}
						for podcasts and radio{" "}
						<span className="text-sec">in minutes</span>
					</p>
					<Button
						asChild
						size="lg"
						className="mb-16 px-12 text-2xl h-14 rounded-full bg-vivid hover:bg-vivid hover:scale-105 transition-all text-black"
					>
						<Link href="/auth">Get Started</Link>
					</Button>
				</section>

				{/* How does it work heading */}
				<h2
					className={`${dm_sans.className} text-4xl md:text-5xl text-vivid text-center mb-12 mt-20`}
				>
					How it works
				</h2>

				{/* Description & Demo Section, pushed below the fold */}
				<section className="container mx-auto mt-10 pb-20">
					<div className="flex flex-col md:flex-row items-center justify-center gap-8 md:gap-16 w-full max-w-6xl mx-auto">
						<div className="flex-1 w-full">
							<h3
								className={`${dm_sans.className} text-2xl text-sec/80 mb-4 text-center`}
							>
								Your description
							</h3>
							<div className="bg-gray-900/50 border border-gray-800 p-8 rounded-2xl h-[400px] flex items-center justify-center backdrop-blur-sm transition-all hover:border-vivid/30 hover:bg-gray-900/70">
								<p
									className={`${dm_sans.className} text-3xl text-sec`}
								>
									"Create an ad for the new IKEA kids
									furniture collection"
								</p>
							</div>
						</div>

						<div className="flex items-center justify-center p-4">
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="36"
								height="36"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								strokeWidth="2"
								strokeLinecap="round"
								strokeLinejoin="round"
								className="text-vivid transform rotate-0 md:rotate-90 lg:rotate-0 opacity-80"
							>
								<path d="M5 12h14"></path>
								<path d="m12 5 7 7-7 7"></path>
							</svg>
						</div>

						<div className="flex-1 w-full">
							<h3
								className={`${dm_sans.className} text-2xl text-sec/80 mb-4 text-center`}
							>
								Beautiful advertisement generated by AI
							</h3>
							<div className="border border-gray-800 rounded-2xl overflow-hidden transition-all hover:border-vivid/30">
								<PlaybackDemo
									jsonPath="/example_recordings/recording-UCdMzmUVLdWwD6yEzstsZVrHeZo2-o9pp4Nv4RF7LZIRXZrq2.json"
									description=""
								/>
							</div>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
